spring.application.name=climalert

climalert.weather.base-url=http://api.weatherapi.com/v1
climalert.weather.api-key=${WEATHER_API_KEY:d303d3b2eb8f431da75213114260607}
climalert.weather.location=Buenos Aires

climalert.alerta.umbral-temperatura=35
climalert.alerta.umbral-humedad=60
climalert.alerta.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

climalert.scheduling.fetch-rate-ms=300000
climalert.scheduling.alert-rate-ms=60000

spring.datasource.url=jdbc:h2:mem:climalert
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

climalert.mail.remitente=no-reply@climalert.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.com.utn.dsi.climalert=INFO
